/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voyage;

import Graphs.Graph;
import Graphs.Vertex;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan O'Hara
 */
public class Simulation extends javax.swing.JFrame {

    /**
     * Creates new form Simulation
     */
    Graph<Const> sistema = new Graph();

    public Simulation() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelDatos = new javax.swing.JDialog();
        ConstBT = new javax.swing.JButton();
        EstreBT = new javax.swing.JButton();
        PanelEst = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        nombreESTTF = new javax.swing.JTextField();
        EstrellaAgre = new javax.swing.JButton();
        ConstelacioinesCB = new javax.swing.JComboBox<>();
        PanelConst = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        nombreConstTF = new javax.swing.JTextField();
        ConstBTAGR = new javax.swing.JButton();
        Simulacion = new javax.swing.JDialog();
        DatosBT = new javax.swing.JButton();
        SimulacionBT = new javax.swing.JButton();

        ConstBT.setText("Constelación");
        ConstBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstBTActionPerformed(evt);
            }
        });

        EstreBT.setText("Estrellas");
        EstreBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstreBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos.getContentPane());
        PanelDatos.getContentPane().setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConstBT)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(EstreBT)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ConstBT)
                .addGap(18, 18, 18)
                .addComponent(EstreBT)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre");

        EstrellaAgre.setText("Agregar");
        EstrellaAgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstrellaAgreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEstLayout = new javax.swing.GroupLayout(PanelEst.getContentPane());
        PanelEst.getContentPane().setLayout(PanelEstLayout);
        PanelEstLayout.setHorizontalGroup(
            PanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(PanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConstelacioinesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelEstLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(PanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreESTTF)
                            .addComponent(EstrellaAgre))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        PanelEstLayout.setVerticalGroup(
            PanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEstLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(ConstelacioinesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(PanelEstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreESTTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(EstrellaAgre)
                .addContainerGap())
        );

        jLabel1.setText("Nombre");

        ConstBTAGR.setText("Agregar");
        ConstBTAGR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstBTAGRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelConstLayout = new javax.swing.GroupLayout(PanelConst.getContentPane());
        PanelConst.getContentPane().setLayout(PanelConstLayout);
        PanelConstLayout.setHorizontalGroup(
            PanelConstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConstLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(PanelConstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreConstTF)
                    .addComponent(ConstBTAGR))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        PanelConstLayout.setVerticalGroup(
            PanelConstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConstLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(PanelConstLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreConstTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConstBTAGR)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout SimulacionLayout = new javax.swing.GroupLayout(Simulacion.getContentPane());
        Simulacion.getContentPane().setLayout(SimulacionLayout);
        SimulacionLayout.setHorizontalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        SimulacionLayout.setVerticalGroup(
            SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DatosBT.setText("Datos");
        DatosBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosBTActionPerformed(evt);
            }
        });

        SimulacionBT.setText("Simulación");
        SimulacionBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimulacionBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DatosBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SimulacionBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(DatosBT)
                .addGap(33, 33, 33)
                .addComponent(SimulacionBT)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DatosBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosBTActionPerformed
        PanelDatos.setModal(true);
        PanelDatos.pack();
        PanelDatos.setLocationRelativeTo(null);
        PanelDatos.setVisible(true);
    }//GEN-LAST:event_DatosBTActionPerformed

    private void ConstBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstBTActionPerformed
        // TODO add your handling code here:
        PanelConst.setModal(true);
        PanelConst.pack();
        PanelConst.setLocationRelativeTo(null);
        PanelConst.setVisible(true);
    }//GEN-LAST:event_ConstBTActionPerformed

    private void SimulacionBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimulacionBTActionPerformed
        // TODO add your handling code here:
        Simulacion.setModal(true);
        Simulacion.pack();
        Simulacion.setLocationRelativeTo(null);
        Simulacion.setVisible(true);
    }//GEN-LAST:event_SimulacionBTActionPerformed

    private void EstreBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstreBTActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (int i = 0; i < sistema.getVertices().getSize(); i++) {
            model.addElement(sistema.getVer(i));
        }
        ConstelacioinesCB.setModel(model);
        if (!sistema.getVertices().isEmpty()) {
            PanelEst.setModal(true);
            PanelEst.pack();
            PanelEst.setLocationRelativeTo(null);
            PanelEst.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No hay Constelaciones!!");
        }
    }//GEN-LAST:event_EstreBTActionPerformed

    private void ConstBTAGRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstBTAGRActionPerformed
        // TODO add your handling code here:
        String nom = nombreConstTF.getText();
        Vertex<Const> temp = new Vertex<>(new Const(nom));
        if (!sistema.contains(temp.retVal())) {
            sistema.addV(temp);
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe esta constellación");
        }
        nombreConstTF.setText("");
    }//GEN-LAST:event_ConstBTAGRActionPerformed

    private void EstrellaAgreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstrellaAgreActionPerformed
        // TODO add your handling code here:
        String nom = nombreESTTF.getText();
        Vertex<Star> temp = new Vertex<>(new Star(nom));
        int pos = ConstelacioinesCB.getSelectedIndex();
        if (!((Const) sistema.getVer(pos).retVal()).getStars().contains(temp)) {
            ((Const) sistema.getVer(pos).retVal()).addStar(temp.retVal());
        } else {
            JOptionPane.showMessageDialog(null, "Ya existe esta Estrella");
        }
        System.out.println(((Const) sistema.getVer(pos).retVal()).getStars());
        nombreESTTF.setText("");
    }//GEN-LAST:event_EstrellaAgreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConstBT;
    private javax.swing.JButton ConstBTAGR;
    private javax.swing.JComboBox<String> ConstelacioinesCB;
    private javax.swing.JButton DatosBT;
    private javax.swing.JButton EstreBT;
    private javax.swing.JButton EstrellaAgre;
    private javax.swing.JDialog PanelConst;
    private javax.swing.JDialog PanelDatos;
    private javax.swing.JDialog PanelEst;
    private javax.swing.JDialog Simulacion;
    private javax.swing.JButton SimulacionBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nombreConstTF;
    private javax.swing.JTextField nombreESTTF;
    // End of variables declaration//GEN-END:variables
}
